### ISSUE TITLE
when 2 ROIs, the second ome.tif output was empty

### ISSUE THREAD

**Issue by hungyiwu** [hungyiwu/pca_analysis_toolkit#3]
First pass trying to recapitulate this issue:
- duplicated the ROI in example file and rename to "mytestroi2" ==> works

Pending more details from the end user.

**Comment by rjp21** [comment]
This issue can be resolved. The issue was not an issue with the program but an issue with my input data. The error was called for and due to the input roi containing points located outside the grid of the ome.tif (pictured):
<img width="458" alt="Screen Shot 2020-04-21 at 7 40 57 PM" src="https://user-images.githubusercontent.com/63072052/79925529-91445200-8408-11ea-95e0-7e23dc38d0df.png">

**Comment by hungyiwu** [comment]
Thanks for investigating into this! I can add one sanity check in the program to skip ROIs with points outside the image, while printing a warning on the screen.

**Comment by hungyiwu** [comment]
implemented in branch `develop`
